'use client';
import { useState } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, FileText, Loader2, MapPin, Search, Users } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Pagination, PaginationContent, PaginationItem } from '@/components/ui/pagination';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { nearbyStations } from '@/lib/stations';
import { type MaintenanceRequest, type Worker, departments, localInput, toISO } from '@/lib/types';

type Plan={request_id:string;station:string;required_crew:number;start_at:string;end_at:string;priority:string};
type Props={requests:MaintenanceRequest[];workers:Worker[];onCreate:(plan:Plan)=>Promise<void>;onOpenJob:(request:MaintenanceRequest)=>void};
function Choice({value,onChange,label,options}:{value:string;onChange:(v:string)=>void;label:string;options:{value:string;label:string}[]}){return <Select items={options} value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="pick" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function MaintenanceRequests({requests,workers,onCreate,onOpenJob}:Props){
 const [search,setSearch]=useState(''),[corridor,setCorridor]=useState('all'),[line,setLine]=useState('all'),[severity,setSeverity]=useState('all'),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[selected,setSelected]=useState<MaintenanceRequest|null>(null);
 const matched=requests.filter(r=>`${r.request_id} ${r.task_type} ${r.corridor_name} ${r.line_type}`.toLowerCase().includes(search.toLowerCase())&&(line==='all'||r.line_type===line)&&(corridor==='all'||r.corridor_name===corridor)&&(severity==='all'||r.defect_severity===Number(severity))&&(status==='all'||(status==='unplanned'?!r.job_id:!!r.job_id)));
 const pages=Math.max(1,Math.ceil(matched.length/20)),current=Math.min(page,pages),shown=matched.slice((current-1)*20,current*20);
 function filter(set:(s:string)=>void,value:string){set(value);setPage(1)}
 return <>
  <div className="request-summary"><div><FileText size={23}/><span><strong>{requests.length}</strong> department requests</span></div><div><Clock3 size={21}/><span><strong>{requests.filter(r=>!r.job_id).length}</strong> awaiting a plan</span></div><div><CheckCircle2 size={21}/><span><strong>{requests.filter(r=>!!r.job_id).length}</strong> linked to jobs</span></div></div>
  <section className="panel requests-panel"><div className="section-header"><div><h2>Maintenance request register</h2></div></div>
   <div className="request-filters"><div className="search-field"><Search size={16}/><input aria-label="Search maintenance requests" value={search} placeholder="Search request ID, task or line" onChange={e=>filter(setSearch,e.target.value)}/></div><Choice label="Filter by corridor" value={corridor} onChange={v=>filter(setCorridor,v)} options={[{value:'all',label:'All corridors'},...Array.from(new Set(requests.map(r=>r.corridor_name))).sort().map(v=>({value:v,label:v}))]}/><Choice label="Filter by line" value={line} onChange={v=>filter(setLine,v)} options={[{value:'all',label:'All lines'},...Array.from(new Set(requests.map(r=>r.line_type))).sort().map(v=>({value:v,label:v}))]}/><Choice label="Filter by defect severity" value={severity} onChange={v=>filter(setSeverity,v)} options={[{value:'all',label:'All severities'},...[5,4,3,2,1].map(v=>({value:String(v),label:`Severity ${v}`}))]}/><Choice label="Filter planning status" value={status} onChange={v=>filter(setStatus,v)} options={[{value:'all',label:'All requests'},{value:'unplanned',label:'Awaiting plan'},{value:'planned',label:'Job created'}]}/></div>
   <div className="request-list-note"><span>{matched.length} matching requests</span><span>Order: severity descending, then source backlog</span></div>
   <Table className="workers-table requests-table"><TableHeader><TableRow><TableHead>Request / task</TableHead><TableHead>Corridor / line</TableHead><TableHead>Severity</TableHead><TableHead>Source backlog</TableHead><TableHead>Duration</TableHead><TableHead>Plan</TableHead></TableRow></TableHeader><TableBody>{shown.map(r=><TableRow key={r.request_id}><TableCell><button className="request-title" onClick={()=>setSelected(r)}><small>{r.request_id} · {r.department}</small><b>{r.task_type}</b></button></TableCell><TableCell><span>{r.corridor_name}</span><small className="table-secondary">{r.line_type}</small></TableCell><TableCell><span className="severity-value">{r.defect_severity}<small>/ 5</small></span></TableCell><TableCell>{r.backlog_age_days} days</TableCell><TableCell>{r.required_duration_mins} min</TableCell><TableCell>{r.job_id?<button className="btn linked-plan" onClick={()=>onOpenJob(r)}><CheckCircle2 size={14}/>{r.job_status!=='Pending'?'View job':'Select crew'}</button>:<button className="btn request-plan" onClick={()=>setSelected(r)}>Plan crew <ArrowRight size={14}/></button>}</TableCell></TableRow>)}</TableBody></Table>
   {!matched.length&&<Empty className="empty-state"><EmptyHeader><EmptyTitle>No matching requests</EmptyTitle><EmptyDescription>Try another search, corridor, line, severity, or planning status.</EmptyDescription></EmptyHeader></Empty>}
   <div className="request-pagination"><span>{matched.length?`${(current-1)*20+1}–${Math.min(current*20,matched.length)} of ${matched.length}`:'0 results'}</span><Pagination aria-label="Maintenance request pages"><PaginationContent><PaginationItem><button className="btn" disabled={current<=1} onClick={()=>setPage(current-1)}>Previous</button></PaginationItem><PaginationItem><span className="page-number">Page {current} of {pages}</span></PaginationItem><PaginationItem><button className="btn" disabled={current>=pages} onClick={()=>setPage(current+1)}>Next</button></PaginationItem></PaginationContent></Pagination></div>
   <p className="roster-note">Request timestamps and backlog are source values. Creating a crew plan does not mark a request as completed.</p>
  </section>
  {selected&&<RequestPlan key={selected.request_id} request={requests.find(r=>r.request_id===selected.request_id)||selected} workers={workers} close={()=>setSelected(null)} onCreate={onCreate} onOpenJob={onOpenJob}/>}
 </>
}
function RequestPlan({request:r,workers,close,onCreate,onOpenJob}:{request:MaintenanceRequest;workers:Worker[];close:()=>void;onCreate:Props['onCreate'];onOpenJob:Props['onOpenJob']}){
 const tomorrow=new Date(Date.now()+86400000+330*60000).toISOString().slice(0,10);
 const [start,setStart]=useState(tomorrow+'T08:00'),[station,setStation]=useState(''),[crew,setCrew]=useState(''),[priority,setPriority]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const end=start&&Number.isFinite(new Date(start).getTime())?localInput(new Date(new Date(toISO(start)).getTime()+r.required_duration_mins*60000).toISOString()):'';
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!station||!priority)throw new Error('Choose a reporting station and priority.');await onCreate({request_id:r.request_id,station,required_crew:Number(crew),start_at:toISO(start),end_at:toISO(end),priority});close()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&close()}><DialogContent className="new-job-modal request-modal"><DialogHeader><span className="eyebrow">{r.request_id} / {r.department}</span><DialogTitle className="modal-title">{r.task_type}</DialogTitle><DialogDescription>{departments[r.department_code]} department · Imported maintenance request</DialogDescription></DialogHeader>
  <div className="request-location"><MapPin size={18}/><div><b>{r.corridor_name}</b><span>{r.line_type}</span><small>Latitude {r.latitude} · Longitude {r.longitude}</small></div></div>
  <div className="request-facts"><div><span>Defect severity</span><b>{r.defect_severity} / 5</b></div><div><span>Backlog in source</span><b>{r.backlog_age_days} days</b></div><div><span>Required duration</span><b>{r.required_duration_mins} min</b></div></div>
  <div className="source-timestamp"><span>Request timestamp in source</span><code>{r.timestamp.replace('T',' ')}</code><small>Timezone not supplied. This is not a scheduled work time.</small></div>
  {r.job_id?<div className="request-already-planned"><p>This request is linked to job <b>{r.job_id}</b>.</p><button className="btn primary" onClick={()=>{close();onOpenJob(r)}}>{r.job_status!=='Pending'?'View job and crew':'Select workers for this job'}<ArrowRight size={16}/></button></div>:<form className="job-form" onSubmit={submit}><div className="request-plan-heading"><Users size={18}/><h3>Plan the crew assignment</h3></div><p className="request-form-note">Choose the crew size, reporting station, and work start. End time uses the request’s required duration.</p><div className="form-two"><label>Reporting station<Choice label="Reporting station" value={station} onChange={setStation} options={[{value:'',label:'Choose a station'},...Array.from(new Set(workers.map(w=>w.station_code))).sort().map(v=>({value:v,label:v}))]}/></label><label>Workers required<input type="number" min={1} max={workers.length} required value={crew} onChange={e=>setCrew(e.target.value)} placeholder="Enter crew size"/></label></div><p className="request-form-note">{station?`Crew will be limited to ${nearbyStations(station).join(', ')}.`:"Choose a reporting station to determine nearby crew locations."}</p><label>Planning priority<Choice label="Planning priority" value={priority} onChange={setPriority} options={[{value:'',label:'Choose a priority'},...['High','Medium','Low'].map(v=>({value:v,label:v}))]}/></label><div className="form-two"><label><span>Start date & time (IST)</span><input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>End date & time (IST)</span><input aria-label="Calculated work end time" type="datetime-local" value={end} readOnly/></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="btn" type="button" onClick={close} disabled={busy}>Cancel</button><button className="btn primary" type="submit" disabled={busy||!station||!crew||!priority||!start}>{busy?<Loader2 size={16} className="spin"/>:<CalendarDays size={16}/>}Create job & select crew<ArrowRight size={16}/></button></div></form>}
 </DialogContent></Dialog>
}
