'use client';
import { useEffect, useState, useCallback } from 'react';
import { TrainFront, ArrowRight, ShieldCheck, Users, Clock3, ClipboardList, CalendarDays, LogOut, Plus, Search, ChevronRight, MapPin, Check, CheckCircle2, CircleDot, ArrowUpRight, RefreshCw, Loader2, X, Wrench, Info, FileText } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { isNearbyStation, nearbyStations } from '@/lib/stations';
import { PdfDownload, DailyReportBar } from './report-download';
import { finalizedCrew } from '@/lib/reports/types';
import Homepage from './homepage';
import ControlCentre from './control-centre/dashboard';
import MaintenanceRequests from './maintenance-requests';
import { type Account, type Worker, type Job, type Booking, type MaintenanceRequest, departments, withinShift, localInput, toISO, formatDate, formatTime } from '@/lib/types';

export type Data={departmentWorkers?:{department_code:string;availability_status:string;count:number}[];departmentRequests?:{department_code:string;total:number;unplanned:number}[];user:Account|null;workers?:Worker[];worker?:Worker;jobs?:Job[];bookings?:Booking[];totalWorkers?:number;requests?:MaintenanceRequest[];requestDataset?:{filename:string;row_count:number}};
async function api(body?:Record<string,unknown>):Promise<any>{const res=await fetch('/api/app',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await res.json() as any;if(!res.ok)throw new Error(data.error||'Something went wrong. Please retry.');return data}
const initials=(name:string)=>name.split(' ').slice(0,2).map(s=>s[0]).join('');
function Brand(){return <span className="app-mark" aria-label="Railway maintenance"><TrainFront size={25}/></span>}
function Pick({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={v=>v!==null&&onChange(v)} items={options}><SelectTrigger className="pick" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Blank({title,description}:{title:string;description:string}){return <Empty className="empty-state"><ClipboardList size={28}/><EmptyHeader><EmptyTitle className="empty-title">{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>}
function Status({value}:{value:string}){return <span className={'pill '+(['High','On Leave'].includes(value)?'red':['Pending','On Duty'].includes(value)?'amber':['Available','Assigned','Acknowledged','Completed'].includes(value)?'green':'gray')}><span className="status-dot"/>{value}</span>}
function Schedule({job}:{job:Job}){return <span>{formatDate(job.start_at)} · {formatTime(job.start_at)} – {formatDate(job.start_at)!==formatDate(job.end_at)?formatDate(job.end_at)+' · ':''}{formatTime(job.end_at)} IST</span>}

export default function Workspace({controlLogin=false,signIn=false,defaultRole='head'}:{controlLogin?:boolean;signIn?:boolean;defaultRole?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[view,setView]=useState('assign'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[activeJob,setActiveJob]=useState<string|null>(null);
 const refresh=useCallback(async()=>{const d=await api();setData(d);return d as Data},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[refresh]);
 useEffect(()=>{if(!data?.user)return;const timer=setInterval(()=>refresh().catch(()=>{}),15000);return()=>clearInterval(timer)},[data?.user?.id,refresh]);
 async function logout(){setBusy(true);try{await api({action:'logout'});setData({user:null});setView('assign');setNotice('');setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data){return <main className="loading"><Brand/>{error?<><p className="error" role="alert">{error}</p><button className="btn" onClick={()=>{setError('');refresh().catch(e=>setError(e.message))}}>Retry connection</button></>:<p><Loader2 className="spin inline" size={18}/> Loading your workspace…</p>}</main>}
 if(!data.user)return controlLogin||signIn?<Login onLogin={refresh} controller={controlLogin} defaultRole={defaultRole}/>:<Homepage/>;
 if(data.user.role==='controller')return <ControlCentre data={data} onLogout={logout} refresh={refresh}/>;
 if(controlLogin)return <main className="login-page"><section className="panel role-gate"><h1>Control Centre</h1><p>You are signed in as {data.user.name}. Sign out to use the controller account.</p><button className="btn primary" onClick={logout}>Sign out</button><a className="btn" href="/">Return to your workspace</a></section></main>;
 const user=data.user,jobs=data.jobs||[],workers=data.workers||[],requests=data.requests||[];
 function openRequestJob(r:MaintenanceRequest){setActiveJob(r.job_id||null);setView(r.job_status!=='Pending'?'scheduled':'assign');setNotice(`Opened crew plan for ${r.request_id}.`)}
 const head=user.role==='head';const pending=jobs.filter(j=>j.status==='Pending');const assigned=jobs.filter(j=>j.status!=='Pending');
 const title=head?view==='assign'?'Crew assignment':view==='roster'?'Worker directory':view==='requests'?'Maintenance requests':'Scheduled jobs':'My assignments';
 return <SidebarProvider style={{'--sidebar-width':'250px'} as React.CSSProperties}>
  <Sidebar className="rail-sidebar"><SidebarHeader className="rail-sidebar-head"><div className="division"><span className="division-icon"><TrainFront size={16}/></span><div>Maintenance<small>{departments[user.department]} department</small></div></div><SidebarTrigger className="desktop-sidebar-toggle"/></SidebarHeader>
   <SidebarContent className="rail-nav"><span className="nav-label">WORKSPACE</span><SidebarMenu>{(head?[{id:'assign',label:'Crew assignment',icon:Users,count:pending.length},{id:'requests',label:'Maintenance requests',icon:FileText,count:requests.length},{id:'scheduled',label:'Scheduled jobs',icon:CalendarDays,count:assigned.length},{id:'roster',label:'Worker directory',icon:ClipboardList,count:workers.length}]:[{id:'assign',label:'My assignments',icon:ClipboardList,count:jobs.length}]).map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-button" isActive={view===n.id} onClick={()=>{setView(n.id);setNotice('')}}><n.icon size={19}/><span>{n.label}</span><b>{n.count}</b></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>

   </SidebarContent><SidebarFooter className="rail-sidebar-foot"><div className="sidebar-user"><div className="avatar">{head?'DH':initials(user.name)}</div><div><b>{head?'Department head':user.name}</b><small>{user.id}</small></div><button disabled={busy} onClick={logout} className="signout" title="Sign out" aria-label="Sign out"><LogOut size={17}/></button></div></SidebarFooter>
  </Sidebar>
  <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="sidebar-toggle"/><span>Operations</span><ChevronRight size={14}/><b>{title}</b></div><div className="topbar-right"><span className="time-zone">Schedules in IST</span><span className="header-divider"/><ShieldCheck size={17}/><span>{departments[user.department]}</span><div className="avatar small">{head?'DH':initials(user.name)}</div></div></header>
   <div className="workspace-content"><div className="page-heading"><div><h1>{title}</h1></div><button className="btn refresh" onClick={()=>{refresh().then(()=>setNotice('Your workspace is up to date.')).catch(e=>setError(e.message))}} aria-label="Refresh workspace"><RefreshCw size={16}/><span>Refresh</span></button></div>
   {error&&<div className="error" role="alert">{error}<button className="dismiss" onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
   {notice&&<div className="success" role="status"><CheckCircle2 size={19}/><span>{notice}</span><button className="dismiss" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
   {head?<><div className="stats-grid"><div className="stat"><span className="stat-icon green"><Users size={21}/></span><div><span>Available in roster</span><strong>{workers.filter(w=>w.availability_status==='Available').length}<small>/ {workers.length} workers</small></strong></div></div><div className="stat"><span className="stat-icon amber"><Wrench size={21}/></span><div><span>Awaiting crew</span><strong>{pending.length.toString().padStart(2,'0')}<small>maintenance jobs</small></strong></div></div><div className="stat"><span className="stat-icon blue"><CalendarDays size={21}/></span><div><span>Crew allocated</span><strong>{assigned.length.toString().padStart(2,'0')}<small>scheduled or completed jobs</small></strong></div></div></div>
    <DailyReportBar jobs={jobs} department={user.department}/>
    {view==='assign'&&<button className="dataset-banner" onClick={()=>setView('requests')}><span className="dataset-banner-icon"><FileText size={22}/></span><span><b>Maintenance requests</b><small>{requests.filter(r=>!r.job_id).length} awaiting a crew plan</small></span><span className="dataset-banner-action">Review requests <ArrowRight size={16}/></span></button>}
    {view==='requests'?<MaintenanceRequests requests={requests} workers={workers} onOpenJob={openRequestJob} onCreate={async(plan)=>{const result=await api({action:'create_from_request',...plan});await refresh();setActiveJob(result.id);setView('assign');setNotice(`Crew plan created from ${plan.request_id}. Tick the workers to assign.`)}}/>:view==='assign'?<AssignmentWorkspace key={activeJob||'queue'} initialJob={activeJob} jobs={pending} workers={workers} bookings={data.bookings||[]} user={user} onSaved={async(message)=>{await refresh();setNotice(message)}}/>:view==='roster'?<Roster workers={workers}/>:<Scheduled jobs={assigned} activeJob={activeJob} onSaved={async()=>{await refresh();setNotice('Job completion confirmed. Control Centre progress is updated.')}}/>}
    </>:<WorkerWorkspace jobs={jobs} worker={data.worker!} onSaved={async()=>{await refresh();setNotice('Your work status has been updated for your department head.')}}/>}
   <div className="workspace-footer"><span><ShieldCheck size={14}/> Crew allocation only. Operational and safety clearance is separate.</span></div>
   </div>
  </main>
 </SidebarProvider>
}
function Login({onLogin,controller=false,defaultRole='head'}:{onLogin:()=>Promise<unknown>;controller?:boolean;defaultRole?:string}){
 const [role,setRole]=useState(defaultRole),[id,setId]=useState(controller?'CONTROL-01':defaultRole==='worker'?'W0002':'HEAD-TRK'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{await api({action:'login',id,password});await onLogin()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="login-page"><section className="login-panel"><div className="login-form"><a href="/" className="login-home-brand"><Brand/><span>RailBlock AI<small>RAILWAY MAINTENANCE</small></span></a><h1>{controller?'Control Centre':'Sign in'}</h1>{controller?<p className="login-intro">RailBlock AI · Unified block planning</p>:<Tabs className="login-tabs" value={role} onValueChange={v=>{setRole(v as string);setId(v==='head'?'HEAD-TRK':'W0002');setError('')}}><TabsList><TabsTrigger value="head"><ShieldCheck size={16}/>Department head</TabsTrigger><TabsTrigger value="worker"><Users size={16}/>Worker</TabsTrigger></TabsList></Tabs>}<form onSubmit={submit}>
 {controller?<label>Controller ID<input value={id} onChange={e=>setId(e.target.value)} autoComplete="username" required/></label>:role==='head'?<label>Department<Pick label="Department" value={id} onChange={setId} options={Object.entries(departments).map(([v,l])=>({value:'HEAD-'+v,label:l+' department'}))}/></label>:<label>Worker ID<input value={id} onChange={e=>setId(e.target.value)} placeholder="e.g. W0002" autoComplete="username" required/></label>}
 <label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" required/></label>{error&&<div className="error" role="alert">{error}</div>}<button disabled={busy} className="btn primary" type="submit">{busy?<Loader2 size={17} className="spin"/>:'Sign in'}{!busy&&<ArrowRight size={17}/>}</button></form><div className="demo-note"><b>Demo accounts</b><p>All demo accounts use <code>RailOps@123</code></p><small>{controller?'Use CONTROL-01 to review all departments and plan blocks.':role==='head'?'Choose Track, Signal, or Traction above.':'Use any worker ID from W0001 to W0203. Only that worker’s assignments will be shown.'}</small><button type="button" className="demo-fill" onClick={()=>setPassword('RailOps@123')}>Use demo password <ArrowUpRight size={14}/></button></div><a className="login-switch" href={controller?'/login':'/control-centre'}>{controller?'Department head or worker sign in':'Control Centre sign in'} <ArrowRight size={14}/></a></div></section></main>
}
function AssignmentWorkspace({jobs,workers,bookings,user,onSaved,initialJob}:{initialJob?:string|null;jobs:Job[];workers:Worker[];bookings:Booking[];user:Account;onSaved:(s:string)=>Promise<void>}){
 const [selectedJob,setSelectedJob]=useState<string|null>(initialJob||null),[createOpen,setCreateOpen]=useState(false);
 const job=jobs.find(j=>j.id===selectedJob)||jobs[0];
 return <div className="assignment-layout"><aside className="jobs-pane"><div className="pane-heading"><div><h2>Maintenance queue</h2><span>{jobs.length} jobs need a crew</span></div><span className="count-badge">{jobs.length}</span></div><button className="btn new-job" onClick={()=>setCreateOpen(true)}><Plus size={17}/> New maintenance job</button><div className="job-stack">{jobs.map(j=><button key={j.id} onClick={()=>setSelectedJob(j.id)} className={'job-tile '+(job?.id===j.id?'active':'')}><div className="tile-meta"><span>{j.id}</span><Status value={j.priority}/></div><h3>{j.title}</h3><div className="job-location"><MapPin size={14}/>{j.station} <span>·</span> {departments[j.department]}</div><div className="tile-bottom"><span><Users size={14}/>{j.required_crew} workers needed</span><ChevronRight size={17}/></div></button>)}</div>{!jobs.length&&<Blank title="Queue is clear" description="Create a maintenance job to assign a crew."/>}<div className="queue-note"><Info size={16}/><p>Sample jobs are marked in their details. Worker availability comes from the supplied roster.</p></div></aside>
 {job?<CrewPicker key={job.id} job={job} workers={workers} bookings={bookings} onSaved={onSaved}/>:<section className="panel"><Blank title="Ready for the next job" description="All current jobs have a crew. Create a job or review Scheduled jobs."/></section>}
 <NewJob open={createOpen} setOpen={setCreateOpen} workers={workers} user={user} onSaved={async(id)=>{setSelectedJob(id);await onSaved('Maintenance job created. Select its crew below.')}}/>
 </div>
}
function CrewPicker({job,workers,bookings,onSaved}:{job:Job;workers:Worker[];bookings:Booking[];onSaved:(s:string)=>Promise<void>}){
 const [start,setStart]=useState(localInput(job.start_at)),[end,setEnd]=useState(localInput(job.end_at)),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[station,setStation]=useState('all'),[available,setAvailable]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const valid=!!start&&!!end&&new Date(start)<new Date(end)&&(!job.source_request||new Date(end).getTime()-new Date(start).getTime()>=job.source_request.required_duration_mins*60000);const si=valid?toISO(start):'',ei=valid?toISO(end):'';
 function reason(w:Worker){if(!isNearbyStation(w.station_code,job.station))return 'Outside nearby stations';if(w.availability_status!=='Available')return w.availability_status;if(!valid)return 'Set job time';if(!withinShift(w.shift,si,ei))return 'Outside shift';if(bookings.some(b=>b.worker_id===w.worker_id&&b.start_at<ei&&b.end_at>si))return 'Time conflict';return ''}
 const nearby=nearbyStations(job.station);
 const eligible=workers.filter(w=>!reason(w));const filtered=workers.filter(w=>isNearbyStation(w.station_code,job.station)&&(station==='all'||w.station_code===station)&&(!available||!reason(w))&&`${w.name} ${w.worker_id} ${w.designation}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(!!reason(a))-Number(!!reason(b))||a.name.localeCompare(b.name));
 const invalidSelected=selected.some(id=>reason(workers.find(w=>w.worker_id===id)!));
 function changeTime(v:string,kind:string){if(kind==='start')setStart(v);else setEnd(v);setSelected([]);setError('')}
 function toggle(id:string){setError('');setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 async function assign(){setBusy(true);setError('');try{await api({action:'assign',job_id:job.id,worker_ids:selected,start_at:si,end_at:ei});await onSaved(`${selected.length} workers assigned to “${job.title}”. They can now see the job in their accounts.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="crew-panel panel"><div className="job-detail"><div className="detail-eyebrow"><span className="eyebrow">JOB DETAILS <span>/ {job.id}</span></span>{!!job.simulated&&<span className="sample-label">Sample job</span>}</div><div className="detail-title"><h2>{job.title}</h2><Status value={job.priority}/></div><p className="detail-location"><MapPin size={15}/><b>{job.station}</b><span>{job.location}</span></p><p className="job-description">{job.description}</p><SourceInfo job={job}/><div className="schedule-fields"><label><span><CalendarDays size={14}/> Start date & time</span><input aria-label="Job start date and time in IST" readOnly={!!job.approved_block} type="datetime-local" value={start} onChange={e=>changeTime(e.target.value,'start')}/></label><label><span><Clock3 size={14}/> End date & time</span><input aria-label="Job end date and time in IST" readOnly={!!job.approved_block} type="datetime-local" value={end} onChange={e=>changeTime(e.target.value,'end')}/></label></div><div className="schedule-foot"><span>IST (UTC+05:30){job.source_request?` · Minimum ${job.source_request.required_duration_mins} min`:""}</span><span><Users size={13}/> Required crew: <b>{job.required_crew}</b></span></div></div>
 {job.source_request&&!valid&&<p className="error crew-error" role="alert">Set a valid schedule of at least {job.source_request.required_duration_mins} minutes.</p>}<div className="crew-heading"><div><h2>Select workers <span>{eligible.length} eligible</span></h2><p>Tick {job.required_crew} nearby workers to build this crew.</p></div><div className="selection-meter"><b>{selected.length}</b><span>/ {job.required_crew}<small>SELECTED</small></span></div></div>
 <div className="nearby-station-note"><MapPin size={15}/><span>Reporting station <b>{job.station}</b> and neighboring roster stations: <b>{nearby.join(', ')}</b></span></div><div className="crew-filters"><div className="search-field"><Search size={16}/><input aria-label="Search workers" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID or designation"/></div><Pick value={station} onChange={setStation} label="Filter nearby home stations" options={[{value:'all',label:'All nearby stations'},...nearby.map(s=>({value:s,label:s}))]}/></div><div className="eligibility-bar"><label><Checkbox checked={available} onCheckedChange={v=>setAvailable(!!v)} aria-label="Show eligible workers only"/> Eligible workers only</label><span>{filtered.length} shown</span></div>
 <div className="crew-table-wrap"><Table className="workers-table"><TableHeader><TableRow><TableHead className="checkbox-cell"><span className="sr-only">Select worker</span></TableHead><TableHead>Worker</TableHead><TableHead>Home station</TableHead><TableHead>Shift (IST)</TableHead><TableHead>Availability</TableHead></TableRow></TableHeader><TableBody>{filtered.map(w=>{const disabled=!!reason(w);const chosen=selected.includes(w.worker_id);return <TableRow key={w.worker_id} data-state={chosen?'selected':undefined} className={disabled?'unavailable':''}><TableCell className="checkbox-cell"><Checkbox aria-label={`Select ${w.name}, ${w.worker_id}`} disabled={disabled||(!chosen&&selected.length>=job.required_crew)||busy} checked={chosen} onCheckedChange={()=>toggle(w.worker_id)}/></TableCell><TableCell><div className="worker-cell"><span className="avatar worker-avatar">{initials(w.name)}</span><div><b>{w.name}</b><small>{w.worker_id} · {w.designation}</small></div></div></TableCell><TableCell>{w.station_code}</TableCell><TableCell><ShiftPill shift={w.shift}/></TableCell><TableCell><Status value={reason(w)||'Available'}/></TableCell></TableRow>})}</TableBody></Table></div>
 {!filtered.length&&<Blank title="No matching workers" description="Try another time, station, or search. Uncheck the eligibility filter to see why workers are unavailable."/>}
 {selected.length>0&&<div className="selected-people">{selected.map(id=><button key={id} onClick={()=>toggle(id)} aria-label={`Remove ${workers.find(w=>w.worker_id===id)?.name}`}><Check size={12}/>{workers.find(w=>w.worker_id===id)?.name}<X size={12}/></button>)}</div>}
 {error&&<div className="error crew-error" role="alert">{error}</div>}
 <div className="assignment-footer"><div><b>{selected.length===job.required_crew?'Your crew is ready':`${job.required_crew-selected.length} more ${job.required_crew-selected.length===1?'worker':'workers'} needed`}</b><small>{selected.length} of {job.required_crew} selected · {valid?`${formatTime(si)}–${formatTime(ei)} IST`:'Set a valid time'}</small></div><button className="btn primary" onClick={assign} disabled={busy||!valid||invalidSelected||selected.length!==job.required_crew}>{busy?<Loader2 className="spin" size={16}/>:<Users size={16}/>}Assign {job.required_crew} workers<ArrowRight size={16}/></button></div>
 </section>
}
function Roster({workers}:{workers:Worker[]}){const [search,setSearch]=useState('');const shown=workers.filter(w=>`${w.worker_id} ${w.name} ${w.station_code} ${w.designation}`.toLowerCase().includes(search.toLowerCase()));return <section className="panel roster-panel"><div className="section-header"><div><h2>Department roster <span className="count-badge">{workers.length}</span></h2></div><div className="search-field"><Search size={16}/><input aria-label="Search directory" placeholder="Search workers or stations" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><Table className="workers-table"><TableHeader><TableRow><TableHead>Worker</TableHead><TableHead>Designation</TableHead><TableHead>Home station</TableHead><TableHead>Shift (IST)</TableHead><TableHead>Roster status</TableHead></TableRow></TableHeader><TableBody>{shown.map(w=><TableRow key={w.worker_id}><TableCell><div className="worker-cell"><span className="avatar worker-avatar">{initials(w.name)}</span><div><b>{w.name}</b><small>{w.worker_id}</small></div></div></TableCell><TableCell>{w.designation}</TableCell><TableCell><b>{w.station_code}</b><small className="table-secondary">{w.station_name}</small></TableCell><TableCell><ShiftPill shift={w.shift}/></TableCell><TableCell><Status value={w.availability_status}/></TableCell></TableRow>)}</TableBody></Table>{!shown.length&&<Blank title="No matching workers" description="Search by a name, worker ID, designation, or station code."/>}<p className="roster-note"><Info size={15}/> Roster availability is an undated dataset snapshot. Job bookings are checked separately when assigning a crew.</p></section>}
function Scheduled({jobs,activeJob,onSaved}:{jobs:Job[];activeJob?:string|null;onSaved:()=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState('');async function complete(id:string){setBusy(id);setError('');try{await api({action:'confirm_completion',job_id:id});await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy('')}}return <div className="scheduled-list">{error&&<p className="error" role="alert">{error}</p>}{!jobs.length&&<section className="panel"><Blank title="No crews assigned yet" description="Choose workers in Crew assignment to schedule your first job."/></section>}{[...jobs].sort((a,b)=>Number(b.id===activeJob)-Number(a.id===activeJob)).map(j=><section className="panel scheduled-card" key={j.id}><div className="scheduled-top"><div><span className="eyebrow">{j.id} {!!j.simulated&&' / SAMPLE JOB'}</span><h2>{j.title}</h2><p><MapPin size={15}/>{j.station} · {j.location}</p></div><div className="schedule-card-actions"><Status value={j.status}/>{finalizedCrew(j)&&<PdfDownload query={{kind:'job',job_id:j.id}}>Schedule & crew PDF</PdfDownload>}</div></div>{j.status==='Awaiting review'&&<div className="completion-review"><p>Every assigned worker has reported completion. Confirm after reviewing the work.</p><button className="btn primary" disabled={!!busy} onClick={()=>complete(j.id)}>Confirm completion</button></div>}{j.completed_at&&<p className="completion-stamp">Completed {formatDate(j.completed_at)} · {formatTime(j.completed_at)} IST</p>}<SourceInfo job={j}/><div className="scheduled-time"><CalendarDays size={18}/><Schedule job={j}/><span><Users size={16}/>{j.crew_count} workers</span></div><div className="scheduled-crew">{j.crew?.map(c=><div key={c.worker_id}><span className="avatar worker-avatar">{initials(c.name)}</span><div><b>{c.name}</b><small>{c.worker_id}</small></div><Status value={c.status}/></div>)}</div></section>)}</div>}
function WorkerWorkspace({jobs,worker,onSaved}:{jobs:Job[];worker:Worker;onSaved:()=>Promise<void>}){const [busy,setBusy]=useState(''),[error,setError]=useState('');async function acknowledge(id:string,action='acknowledge'){setBusy(id);setError('');try{await api({action,job_id:id});await onSaved()}catch(e){setError((e as Error).message)}finally{setBusy('')}}return <><div className="worker-summary"><div className="worker-summary-icon"><Users size={26}/></div><div><span className="eyebrow">YOUR ROSTER PROFILE</span><h2>{worker.designation}</h2><p>{worker.worker_id} <span>·</span> {worker.station_code} home station <span>·</span> Shift {worker.shift} IST</p></div><div className="worker-job-count"><strong>{jobs.length}</strong><span>assigned jobs</span></div></div>{error&&<p className="error" role="alert">{error}</p>}<DailyReportBar jobs={jobs} worker/><div className="section-heading"><h2>Your job schedule</h2><span><CircleDot size={13}/> Updates every 15 seconds</span></div>{!jobs.length?<section className="panel"><Blank title="You’re all caught up" description="When your department head assigns you a job, its location and scheduled time will appear here."/></section>:<div className="worker-jobs">{jobs.map(j=><article className="panel worker-job" key={j.id}><div className="worker-job-date"><CalendarDays size={24}/><b>{new Date(j.start_at).toLocaleDateString('en-IN',{day:'2-digit',timeZone:'Asia/Kolkata'})}</b><span>{new Date(j.start_at).toLocaleDateString('en-IN',{month:'short',timeZone:'Asia/Kolkata'})}</span></div><div className="worker-job-main"><div className="worker-job-meta"><span className="eyebrow">{j.id}{!!j.simulated?' / SAMPLE JOB':''}</span><Status value={j.my_status||'Assigned'}/></div><h2>{j.title}</h2><p>{j.description}</p><SourceInfo job={j}/><div className="worker-job-details"><span><MapPin size={17}/>{j.station} · {j.location}</span><span><Clock3 size={17}/><Schedule job={j}/></span><span><Users size={17}/>You are one of {j.crew_count} assigned workers</span></div><div className="worker-job-bottom"><span>Assigned by {departments[j.department]} department head</span>{j.my_status==='Assigned'?<button className="btn primary" disabled={!!busy} onClick={()=>acknowledge(j.id)}>{busy===j.id?<Loader2 className="spin" size={16}/>:<Check size={16}/>}Acknowledge job</button>:j.my_status==='Acknowledged'?<button className="btn primary" disabled={!!busy} onClick={()=>acknowledge(j.id,'start_work')}>Start work</button>:j.my_status==='In progress'?<button className="btn primary" disabled={!!busy} onClick={()=>acknowledge(j.id,'complete_work')}>Report work completed</button>:<span className="acknowledged"><CheckCircle2 size={18}/>{j.status==='Completed'?'Completion confirmed':'Awaiting head review'}</span>}</div></div></article>)}</div>}</>}
function NewJob({open,setOpen,workers,user,onSaved}:{open:boolean;setOpen:(v:boolean)=>void;workers:Worker[];user:Account;onSaved:(id:string)=>Promise<void>}){
 const tomorrow=new Date(Date.now()+86400000+330*60000).toISOString().slice(0,10);const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[station,setStation]=useState('TNA'),[location,setLocation]=useState(''),[priority,setPriority]=useState('Medium'),[count,setCount]=useState(6),[start,setStart]=useState(tomorrow+'T08:00'),[end,setEnd]=useState(tomorrow+'T10:00'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const res=await api({action:'create',title,description,station,location,priority,required_crew:count,start_at:toISO(start),end_at:toISO(end)});await onSaved(res.id);setOpen(false);setTitle('');setDescription('');setLocation('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="new-job-modal"><DialogHeader><DialogTitle className="modal-title">New maintenance job</DialogTitle><DialogDescription>Create a {departments[user.department].toLowerCase()} job, then manually select its crew.</DialogDescription></DialogHeader><form onSubmit={submit} className="job-form"><label>Problem / job title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Inspect loose rail fastenings"/></label><label>Work instructions<textarea required maxLength={1500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the problem and the work to be carried out." rows={3}/></label><div className="form-two"><label>Station<Pick label="Job station" value={station} onChange={setStation} options={Array.from(new Set(workers.map(w=>w.station_code))).sort().map(s=>({value:s,label:s}))}/></label><label>Work location<input required maxLength={180} value={location} onChange={e=>setLocation(e.target.value)} placeholder="Section / yard / asset"/></label></div><div className="form-two"><label>Priority<Pick label="Job priority" value={priority} onChange={setPriority} options={['High','Medium','Low'].map(s=>({value:s,label:s}))}/></label><label>Workers required<input type="number" min={1} max={100} required value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><div className="form-two"><label>Start date & time (IST)<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date & time (IST)<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={busy} type="submit">{busy?<Loader2 className="spin" size={16}/>:<Plus size={16}/>}Create job & select crew</button></div></form></DialogContent></Dialog>
}

function SourceInfo({job}:{job:Job}){const r=job.source_request;if(!r)return null;return <div className="source-info"><FileText size={15}/><div><b>{r.request_id}</b><span>{r.department} · {r.required_duration_mins} min required · {r.line_type}</span><small>Latitude {r.latitude} · Longitude {r.longitude}</small></div><span className="pill green">CSV request</span></div>}

function ShiftPill({shift}:{shift:string}){return <span className={`shift-pill shift-${shift[0].toLowerCase()}`}><span className="shift-dot"/><b>Shift {shift[0]}</b><span>{shift.slice(3,-1)}</span></span>}
