'use client';
import { useEffect, useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
export default function ModelTraining(){
 const [data,setData]=useState<any>(null),[csv,setCsv]=useState(''),[filename,setFilename]=useState(''),[source,setSource]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function request(body?:any){const r=await fetch('/api/models',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);return d}
 async function load(){setData(await request())}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function run(body:any){setBusy(true);setError('');try{await request(body);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function template(){const url=URL.createObjectURL(new Blob(['section_id,hour_start,freight_count,coverage_complete,source_reference\r\n'],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='freight-observation-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="panel op-card"><h2>Freight forecasting model</h2><p>{data?.status||'Loading model register…'}</p><p>Train from recorded freight movements. Passenger timetable entries are not freight observations. A model is activated only after it beats the comparison baseline and you review its results.</p>{error&&<p className="error" role="alert">{error}</p>}<ul>{(data?.requirements||[]).map((r:string)=><li key={r}>{r}</li>)}</ul><div className="op-controls"><button className="btn" onClick={template}><Download size={15}/>History CSV template</button><label>Observed history CSV<input type="file" accept=".csv" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2_000_000){setError('Use a CSV smaller than 2 MB.');setCsv('');setFilename('');return}setCsv(await f.text());setFilename(f.name)}}/></label></div><label className="op-review">Observation source and collection method<textarea value={source} rows={3} maxLength={1000} onChange={e=>setSource(e.target.value)} placeholder="Source system or register, dates, sections and how complete hourly coverage was established."/></label><div className="op-controls"><button className="btn primary" disabled={busy||!csv||!source.trim()} onClick={()=>run({action:'train',csv,source})}>{busy?<Loader2 size={16} className="spin"/>:null}Train and evaluate candidate</button><span className="metric-note">{filename||'No history file selected'}</span></div>
 {!!data?.runs.length&&<div className="op-table-wrap"><table><thead><tr><th>Candidate</th><th>Chronological holdout</th><th>Prediction error (trains/hour)</th><th>Review</th></tr></thead><tbody>{data.runs.map((m:any)=><tr key={m.id}><td>{m.id}<small>{m.rows} hourly observations · {m.observed_movements} freight entries</small><small>{m.source}</small></td><td>{m.holdout_start.slice(0,10)} – {m.holdout_end.slice(0,10)}<small>Last 14 days held out</small></td><td>Model MAE: {m.mae}<small>Baseline MAE: {m.baseline_mae} · model RMSE: {m.rmse}</small></td><td>{data.active===m.id?<b>Active</b>:<button className="btn" disabled={busy||!m.eligible_for_activation} onClick={()=>run({action:'activate',id:m.id})}>Activate reviewed model</button>}<small>{m.status}</small></td></tr>)}</tbody></table></div>}
 <p className="metric-note">Failure-risk ML still requires asset identities, inspection histories and observed failures. The maintenance CSV contains severity and backlog, so operational priority remains an explained rule score.</p>
 </section>;
}
