'use client';
import { useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, Download, FileUp, Loader2, Plus, RefreshCw, TrainFront, X } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { corridors, importHeaders, type OperationsInput } from '@/lib/operations-types';
import { formatDate, formatTime, localInput, type MaintenanceRequest } from '@/lib/types';
import { PdfDownload } from '../report-download';
import ModelTraining from './model-training';

const tomorrow=()=>new Date(Date.now()+86400000+330*60000).toISOString().slice(0,10);
async function api(body?:unknown,id?:string){const r=await fetch('/api/operations'+(id?'?id='+encodeURIComponent(id):''),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Request failed.');return d}
function download(text:string,name:string){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const when=(s:string)=>`${formatDate(s)} · ${formatTime(s)} IST`;
const labels:Record<string,string>={sections:'Sections',movements:'Train timetable',windows:'Work windows',tasks:'Prepared requests'};
const fieldNames:Record<string,string>={request_id:'Maintenance request',section_id:'Work section',station:'Reporting station',crew:'Workers required',release_at:'Earliest start (IST)',due_at:'Complete by (IST)',machine:'Machine pool (optional)',power:'Power isolation required / available',compatibility_group:'Joint work group (optional)',compatibility_reference:'Compatibility review reference',location_reference:'Exact work location / inspection reference',id:'Record ID',corridor:'Corridor',name:'Section name',from_station:'From station code',to_station:'To station code',source:'Source / verification reference',train_no:'Train number / movement ID',kind:'Train type',start_at:'Start / entry (IST)',end_at:'End / exit (IST)',traffic_complete:'All passenger, freight and restrictions checked for this window',reference:'Work window and traffic verification reference'};

export default function Operations({refreshJobs}:{refreshJobs:()=>Promise<unknown>}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('plan'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[start,setStart]=useState(tomorrow),[horizon,setHorizon]=useState(7),[selected,setSelected]=useState<string[]>([]),[plan,setPlan]=useState<any>(null),[editor,setEditor]=useState<{kind:string;record:any}|null>(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[review,setReview]=useState(''),[reason,setReason]=useState(''),[reportDay,setReportDay]=useState(tomorrow);
 async function load(){const d=await api();setData(d);return d}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function perform(body:any){setBusy(true);setError('');setNotice('');try{const result=await api({...body,...(!['accept','reject','release'].includes(body.action)?{revision:data.revision}:{})});if(result.payload){setPlan(result);setReportDay(result.payload.config.start_date);setReview('')}setNotice(result.message||'Saved.');await load();if(body.action==='release')await refreshJobs();return result}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 if(!data)return <section className="panel op-empty">{error?<p className="error">{error}</p>:<Loader2 className="spin"/>}<button className="btn" onClick={()=>load().catch(e=>setError(e.message))}>Load planning register</button></section>;
 const input=data.input as OperationsInput;
 const prepared=input.tasks.filter(t=>!data.requests.find((r:MaintenanceRequest)=>r.request_id===t.request_id)?.job_id);
 const actualSelected=selected.filter(id=>prepared.some(t=>t.request_id===id));
 const requestList=(data.requests as MaintenanceRequest[]).filter(r=>(filter==='all'||r.corridor_name===filter)&&`${r.request_id} ${r.task_type} ${r.department_code}`.toLowerCase().includes(search.toLowerCase()));
 const records=tab==='tasks'?requestList:tab in labels?(input as any)[tab].filter((r:any)=>{const corridor=r.corridor||input.sections.find(s=>s.id===r.section_id)?.corridor;return (filter==='all'||filter===corridor)&&JSON.stringify(r).toLowerCase().includes(search.toLowerCase())}):[];
 const addRecord=(kind:string,record:any={})=>setEditor({kind,record});
 const btime=(m:number)=>new Date(Date.parse(plan.payload.config.start_date+'T00:00:00+05:30')+m*60000).toISOString();
 const stale=plan&&plan.status!=='Released'&&plan.input_revision!==data.revision;
 return <div className="operations-workspace">
  <div className="op-tabs" role="tablist">{[{id:'plan',name:'Plans & release'},...Object.entries(labels).map(([id,name])=>({id,name})),{id:'sources',name:'Sources & settings'}].map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} onClick={()=>{setTab(t.id);setPage(0);setSearch('')}}>{t.name}</button>)}<button className="btn op-refresh" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={15}/>Refresh</button></div>
  {error&&<div className="error" role="alert">{error}<button className="dismiss" aria-label="Dismiss" onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="success" role="status"><CheckCircle2 size={16}/>{notice}</div>}
  <div className="op-counts"><span><b>{data.requests.length}</b> source requests</span><span><b>{prepared.length}</b> prepared for planning</span><span><b>{input.movements.length}</b> train movements</span><span><b>{input.windows.filter(w=>w.traffic_complete).length}/{input.windows.length}</b> windows with traffic checked</span></div>
  {!!data.alerts?.length&&<div className="error" role="alert"><b>Released work needs controller review</b>{data.alerts.map((a:any)=><p key={a.plan_id+a.message}>{a.plan_id} · {a.message}</p>)}</div>}
  {tab==='plan'?<>
   <section className="panel op-card"><h2>Create a block plan</h2><p>Choose prepared maintenance requests. The schedule uses saved train movements, work windows and the available worker roster.</p><div className="op-controls"><label>Begins (IST)<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={1}>Daily · 1 day</option><option value={7}>Weekly · 7 days</option><option value={30}>Monthly · 30 days</option></select></label><button className="btn primary" disabled={busy||!actualSelected.length} onClick={()=>perform({action:'generate',start_date:start,horizon,request_ids:actualSelected})}>{busy?<Loader2 className="spin" size={16}/>:<CalendarDays size={16}/>}Generate for {actualSelected.length} requests</button></div>
    {!prepared.length?<div className="op-empty"><p>Prepare requests with their section, exact location, crew size and deadline, then record work windows.</p><button className="btn" onClick={()=>setTab('tasks')}>Prepare maintenance requests</button></div>:<div className="op-selection">{prepared.map(t=>{const r=data.requests.find((r:MaintenanceRequest)=>r.request_id===t.request_id);return <label key={t.request_id}><input type="checkbox" checked={actualSelected.includes(t.request_id)} onChange={e=>setSelected(old=>e.target.checked?[...old,t.request_id]:old.filter(id=>id!==t.request_id))}/><span><b>{t.request_id} · {r?.task_type}</b><small>{r?.department_code} · {t.section_id} · {r?.required_duration_mins} min · {t.crew} workers</small></span></label>})}</div>}
   </section>
   {!!data.plans.length&&<label className="op-history">Saved plan<select value={plan?.id||''} onChange={async e=>{if(!e.target.value)return;try{const p=await api(undefined,e.target.value);setPlan(p);setReportDay(p.payload.config.start_date)}catch(e){setError((e as Error).message)}}}><option value="">Choose a saved plan</option>{data.plans.map((p:any)=><option key={p.id} value={p.id}>{p.id} · {p.status} · {when(p.created_at)}</option>)}</select></label>}
   {plan&&<section className="panel op-card"><div className="op-plan-heading"><div><h2>{plan.id} <span className={'pill '+(plan.status==='Released'?'green':'gray')}>{plan.status}</span></h2><p>{plan.payload.config.horizon} days from {plan.payload.config.start_date} · revision {plan.revision} · solver {plan.payload.solver_status}</p></div><PdfDownload query={{kind:'operations',plan_id:plan.id,revision:plan.revision}}>Plan PDF</PdfDownload></div>
    {stale&&<p className="error">Inputs or released work changed since this run. Generate a revised draft before approval.</p>}
    {plan.release_issues.length>0&&plan.status!=='Released'&&<div className="op-readiness"><b>Before release</b><ul>{plan.release_issues.slice(0,6).map((s:string)=><li key={s}>{s}</li>)}</ul></div>}
    <div className="op-comparison"><span><b>{plan.payload.blocks.length}</b> blocks</span><span><b>{plan.payload.blocks.reduce((n:number,b:any)=>n+b.tasks.length,0)}</b> scheduled requests</span><span><b>{plan.payload.comparison.saved_minutes} min</b> saved for {plan.payload.comparison.tasks} matched requests</span><span><b>{plan.payload.unscheduled.length}</b> deferred</span></div><p className="metric-note">{plan.payload.comparison.note} Named crews are selected by department heads after release.</p>
    <div className="op-controls"><label>Daily plan PDF<input type="date" value={reportDay} onChange={e=>setReportDay(e.target.value)}/></label><PdfDownload query={{kind:'operations',plan_id:plan.id,revision:plan.revision,date:reportDay}}>Download day</PdfDownload>{!['Released','Rejected'].includes(plan.status)&&<><button className="btn" disabled={busy} onClick={()=>perform({action:'generate',start_date:start,horizon,request_ids:plan.payload.input.tasks.map((t:any)=>t.id),parent_id:plan.id})}>Replan with current inputs</button><button className="btn" disabled={busy} onClick={()=>{setReview('reject');setReason('')}}>Reject</button><button className="btn primary" disabled={busy||stale||!plan.payload.blocks.length||plan.status==='Accepted'} onClick={()=>{setReview('accept');setReason('')}}>Accept</button><button className="btn primary" disabled={busy||stale||plan.status!=='Accepted'||!!plan.release_issues.length} onClick={()=>{setReview('release');setReason('')}}>Release department jobs</button></>}</div>
    <div className="op-table-wrap"><table><thead><tr><th>Block / section</th><th>Start – end (IST)</th><th>Requests</th><th>Department / crew</th></tr></thead><tbody>{plan.payload.blocks.map((b:any)=><tr key={b.id}><td>{b.section_id}<small>{b.line} · both lines reserved</small></td><td>{when(btime(b.start))}<small>to {when(btime(b.end))} · {b.duration} min</small></td><td>{b.tasks.map((id:string)=><div key={id}>{id}<small>{plan.payload.input.tasks.find((t:any)=>t.id===id)?.title}</small></div>)}</td><td>{b.tasks.map((id:string)=>{const t=plan.payload.input.tasks.find((t:any)=>t.id===id);return <div key={id}>{t.department} · {t.crew} workers<small>{t.station} · {t.machine||'No machine'}</small></div>})}</td></tr>)}</tbody></table></div>
    {!!plan.payload.unscheduled.length&&<details><summary>{plan.payload.unscheduled.length} deferred requests</summary>{plan.payload.unscheduled.map((t:any)=><p key={t.id}><b>{t.id}</b> — {t.reason}</p>)}</details>}
   </section>}
  </>:tab==='sources'?<>
   <section className="panel op-card"><h2>Timetables for the supplied corridors</h2><p>{data.reference.status} · researched {data.reference.researched_at}</p><ul>{data.reference.notes.map((s:string)=><li key={s}>{s}</li>)}</ul><div className="op-controls"><label>Reference begins<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Days<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}><option value={1}>1</option><option value={7}>7</option><option value={30}>30</option></select></label><button className="btn primary" disabled={busy} onClick={()=>perform({action:'reference',start_date:start,horizon})}><TrainFront size={16}/>Add researched timetable</button></div><p className="metric-note">Re-importing preserves manually corrected records. No work windows or approvals are created from public timetable gaps.</p>
    <div className="op-table-wrap"><table><thead><tr><th>Corridor</th><th>Train</th><th>Direction</th><th>Departure / arrival IST</th><th>Reference</th></tr></thead><tbody>{data.reference.services.map((s:any)=><tr key={s.corridor+s.train_no}><td>{s.corridor}</td><td>{s.train_no}<small>{s.name}</small></td><td>{s.from} → {s.to}</td><td>{s.departure} – {s.arrival}{s.arrival<s.departure?' (+1 day)':''}<small>{s.frequency}</small></td><td><a href={s.source} target="_blank" rel="noreferrer">Source timetable</a></td></tr>)}</tbody></table></div>
   </section><ModelTraining/><Settings input={input} busy={busy} save={settings=>perform({action:'settings',...settings})}/>
   <section className="panel op-card"><h2>Saved review history</h2>{data.audit.map((a:any)=><p key={a.id}><b>{a.action}</b> · {a.reason}<small>{a.actor} · {when(a.created_at)}</small></p>)}</section>
  </>:<section className="panel op-card"><div className="op-plan-heading"><div><h2>{labels[tab]}</h2><p>{tab==='tasks'?'Source task, severity and duration remain unchanged. Add the missing planning details.':tab==='windows'?'Record the period considered for maintenance. Confirm traffic coverage only after checking passenger, freight and restrictions.':tab==='movements'?'Edit an arrival or add a delayed freight movement, then generate a revised plan.':'Define work sections within the three maintenance corridors.'}</p></div>{tab!=='tasks'&&<button className="btn primary" disabled={busy} onClick={()=>addRecord(tab)}><Plus size={15}/>Add record</button>}</div>
   <div className="op-controls"><label>Corridor<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="all">All three corridors</option>{corridors.map(c=><option key={c}>{c}</option>)}</select></label><label>Search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="ID, task or train"/></label><button className="btn" onClick={()=>download(importHeaders[tab].join(',')+'\r\n',`railblock-${tab}-template.csv`)}><Download size={15}/>CSV template</button><label className="btn op-file"><FileUp size={15}/>Import CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>1_000_000)setError('Choose a CSV smaller than 1 MB.');else await perform({action:'import',kind:tab,csv:await f.text()});e.target.value=''}}}/></label></div>
   <div className="op-table-wrap"><table><thead><tr><th>Record</th><th>Location / details</th><th>Time / readiness</th><th>Action</th></tr></thead><tbody>{records.slice(page*15,page*15+15).map((r:any)=>{const details=tab==='tasks'?input.tasks.find(t=>t.request_id===r.request_id):r;return <tr key={r.request_id||r.id}><td><b>{r.request_id||r.id}</b><small>{r.task_type||r.train_no||r.name||r.reference}</small></td><td>{r.corridor_name||r.corridor||input.sections.find(s=>s.id===r.section_id)?.corridor}<small>{r.department_code?`${r.department_code} · ${r.line_type} · ${r.required_duration_mins} min · severity ${r.defect_severity}`:r.section_id||`${r.from_station} – ${r.to_station}`}</small></td><td>{tab==='tasks'?(r.job_id?`Job: ${r.job_id}`:details?'Prepared':'Needs planning details'):r.start_at?<>{when(r.start_at)}<small>to {when(r.end_at)}</small>{tab==='windows'&&<small>{r.traffic_complete?'Traffic record checked':'Traffic coverage incomplete'}</small>}</>:r.source}</td><td><button className="btn" disabled={busy||!!r.job_id} onClick={()=>addRecord(tab,details||{request_id:r.request_id})}>{tab==='tasks'&&!details?'Prepare':'Edit'}</button>{details&&<button className="btn" disabled={busy||!!r.job_id} onClick={()=>perform({action:'remove_record',kind:tab,id:r.request_id||r.id})}>Remove</button>}</td></tr>})}</tbody></table>{!records.length&&<p className="op-empty">No matching records. Add a record or import the CSV template.</p>}</div>
   <div className="op-pagination"><span>{records.length} records</span><button className="btn" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button className="btn" disabled={(page+1)*15>=records.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </section>}
  {editor&&<RecordEditor key={editor.kind+JSON.stringify(editor.record)} {...editor} data={data} busy={busy} error={error} close={()=>setEditor(null)} save={async record=>{const r=await perform({action:'save_record',kind:editor.kind,record});if(r)setEditor(null)}}/>}
  <Dialog open={!!review} onOpenChange={v=>!v&&!busy&&setReview('')}><DialogContent><DialogHeader><DialogTitle>{review==='release'?'Release jobs to departments':review==='accept'?'Accept this plan':'Reject this plan'}</DialogTitle><DialogDescription>{review==='release'?'Create one pending crew job per scheduled request. Department heads will select the workers manually. This records local planning approval; it does not operate railway signalling.':'Record your review and its reason.'}</DialogDescription></DialogHeader><label className="op-review">Review reason<textarea rows={3} value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="btn primary" disabled={busy||!reason.trim()} onClick={()=>perform({action:review,plan_id:plan.id,revision:plan.revision,reason})}>{busy?'Saving…':'Save decision'}</button></DialogContent></Dialog>
 </div>;
}

function RecordEditor({kind,record,data,busy,error,close,save}:{kind:string;record:any;data:any;busy:boolean;error:string;close:()=>void;save:(record:any)=>Promise<void>}){
 const keys=importHeaders[kind],day=tomorrow();
 const initial=Object.fromEntries(keys.map(key=>[key,record[key]??(['power','traffic_complete'].includes(key)?false:key==='crew'?1:key==='kind'?'Passenger':key==='corridor'?corridors[0]:['start_at','release_at'].includes(key)?`${day}T06:00:00+05:30`:['end_at','due_at'].includes(key)?`${day}T14:00:00+05:30`:key==='id'?`${kind.slice(0,3).toUpperCase()}-${crypto.randomUUID().slice(0,8)}`:'')]));
 const [values,setValues]=useState<any>(initial);
 const source=data.requests.find((r:MaintenanceRequest)=>r.request_id===values.request_id);
 function options(key:string):{value:string;label:string}[]|null{
  if(key==='section_id')return data.input.sections.filter((s:any)=>!source||s.corridor===source.corridor_name).map((s:any)=>({value:s.id,label:s.name}));
  if(key==='request_id')return data.requests.filter((r:any)=>!r.job_id).map((r:any)=>({value:r.request_id,label:`${r.request_id} · ${r.task_type} · ${r.corridor_name}`}));
  if(key==='station')return data.stations.map((s:string)=>({value:s,label:s}));
  if(key==='corridor')return corridors.map(c=>({value:c,label:c}));
  if(key==='kind')return ['Passenger','Freight'].map(c=>({value:c,label:c}));
  if(key==='machine')return [{value:'',label:'No machine'},...Object.keys(data.input.machines).map(c=>({value:c,label:c}))];
  return null;
 }
 return <Dialog open onOpenChange={v=>!v&&!busy&&close()}><DialogContent className="op-editor"><DialogHeader><DialogTitle>{kind==='tasks'?'Prepare maintenance request':`Save ${labels[kind].toLowerCase()} record`}</DialogTitle><DialogDescription>{kind==='tasks'?'Use inspected work location and department requirements. A shared group permits joint work only with a compatibility review reference.':'All times use IST. Use the next date when an interval crosses midnight.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save(values)}}><div className="op-form-grid">{keys.map(key=>{
  const opts=options(key),time=['start_at','end_at','release_at','due_at'].includes(key),check=['power','traffic_complete'].includes(key),optional=['machine','compatibility_group','compatibility_reference'].includes(key);
  return <label key={key} className={check?'op-check':''}>{check?<><input type="checkbox" checked={values[key]} onChange={e=>setValues({...values,[key]:e.target.checked})}/>{fieldNames[key]}</>:<>{fieldNames[key]||key}{opts?<select value={values[key]} required={!optional} disabled={key==='request_id'&&!!record.request_id} onChange={e=>setValues({...values,[key]:e.target.value,...(key==='request_id'?{section_id:''}:{})})}><option value="">{optional?'None':'Select'}</option>{opts.filter(o=>o.value).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={time?'datetime-local':key==='crew'?'number':'text'} value={time?(Number.isFinite(Date.parse(values[key]))?localInput(values[key]):''):values[key]} required={!optional} min={key==='crew'?1:undefined} max={key==='crew'?100:undefined} readOnly={key==='id'&&!!record.id} onChange={e=>setValues({...values,[key]:time?(e.target.value?e.target.value+':00+05:30':''):key==='crew'?Number(e.target.value):e.target.value})}/>}</>}</label>
 })}</div>{source&&<p className="metric-note">Source: {source.department_code} · {source.corridor_name} · {source.line_type} · {source.required_duration_mins} minutes work.</p>}{error&&<p className="error">{error}</p>}<div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={close}>Cancel</button><button className="btn primary" disabled={busy}>Save record</button></div></form></DialogContent></Dialog>;
}
function Settings({input,busy,save}:{input:OperationsInput;busy:boolean;save:(settings:any)=>Promise<any>}){
 const [headway,setHeadway]=useState(input.headway),[setup,setSetup]=useState(input.setup),[machines,setMachines]=useState(input.machines),[newMachine,setNewMachine]=useState('');
 return <section className="panel op-card"><h2>Planning allowances and machine pools</h2><p>These are configurable planning inputs. The default five-minute train buffer and ten-minute allowance are project settings.</p><div className="op-controls"><label>Train buffer (minutes)<input type="number" min={1} max={120} value={headway} onChange={e=>setHeadway(Number(e.target.value))}/></label><label>Setup / clearance (minutes)<input type="number" min={0} max={120} value={setup} onChange={e=>setSetup(Number(e.target.value))}/></label>{Object.entries(machines).map(([key,value])=><label key={key}>{key} units<input type="number" min={0} max={100} value={value} onChange={e=>setMachines({...machines,[key]:Number(e.target.value)})}/></label>)}<label>New machine pool<input value={newMachine} placeholder="e.g. tower-car" onChange={e=>setNewMachine(e.target.value)}/></label><button className="btn" disabled={!newMachine.trim()} onClick={()=>{setMachines({...machines,[newMachine.trim()]:1});setNewMachine('')}}>Add pool</button><button className="btn primary" disabled={busy} onClick={()=>save({headway,setup,machines})}>Save settings</button></div></section>;
}
